export const APP = {
  ID: "id",
  NAME: "name",
  DEPARTURE_STATION: "departure station",
  ARRIVAL_STATION: "arrival station",
  DEPARTURE_TIME: "departure time",
  ARRIVAL_TIME: "arrival time",
  RANGE_TIME: "range time",
  PRICE: "price",
  SEAT_TYPE: "seat type",
  REQUIRED_FIELD: "fill input please",
  FIRST_NAME: "First name",
  ENTER_FIRST_NAME: "first name",
  SAVE: "save",
  USERNAME: "Username",
  FIRSTNAME: "Firstname",
  LASTNAME: "Lastname",
  BIRTHDATE: "Birthdate",
  PHONENUMBER: "Phonenumber",
  ADDRESS: "Address",
  GENDER: "Gender",
  IMAGEURL: "Imageurl",
  CANCEL: "reset",
};
